Traceback (most recent call last):
  File "C:\Users\USUARIO\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\USUARIO\AppData\Roaming\Python\Python39\site-packages\nbclient\client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\USUARIO\AppData\Roaming\Python\Python39\site-packages\nbclient\util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\USUARIO\AppData\Roaming\Python\Python39\site-packages\nbclient\util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\USUARIO\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\USUARIO\AppData\Roaming\Python\Python39\site-packages\nbclient\client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "C:\Users\USUARIO\AppData\Roaming\Python\Python39\site-packages\nbclient\client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\USUARIO\AppData\Roaming\Python\Python39\site-packages\nbclient\client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd 
import numpy as np # numpy y pandas to data wrangling 
from datetime import datetime, timedelta # to work w date
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_4220/3738376554.py[0m in [0;36m<module>[1;34m[0m
[0;32m      4[0m [1;32mimport[0m [0mmatplotlib[0m[1;33m.[0m[0mpyplot[0m [1;32mas[0m [0mplt[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [1;32mimport[0m [0mseaborn[0m [1;32mas[0m [0msns[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 6[1;33m [1;32mfrom[0m [0mgoogle[0m[1;33m.[0m[0mcolab[0m [1;32mimport[0m [0mdrive[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;31mModuleNotFoundError[0m: No module named 'google.colab'
ModuleNotFoundError: No module named 'google.colab'

